DELETE FROM lyt_estadocuentadetalle;
DELETE FROM lyt_estadocuenta;
DELETE FROM rhm_empleadoperfil;
INSERT INTO rhm_empleadoperfil (id_perfil,perfil) VALUES(1,'Promotor'),(2,'Cliente');
DELETE FROM rhm_genero;
INSERT INTO rhm_genero (id_genero,genero) VALUES(1,'MASCULINO'),(1,'FEMENIDO');
DELETE FROM rhm_tipocliente;
INSERT INTO rhm_tipocliente (id_tipo_cliente,tipo_cliente) VALUES(1,'RECIDENCIAL'),(2,'COMERCIAL'),(3,'SOLO EN LINEA'),(4,'MIGRACIONES');
DELETE FROM lyt_tiposervicio;
INSERT INTO lyt_tiposervicio (tipo_servicio) VALUES('ALTA NUEVA'),('ACTIVACIONES'),('UPSELL'),('OTROS SERVICIOS'),('PORTABILIDADES');
DELETE FROM rhm_empleadotipo;
INSERT INTO rhm_empleadotipo (empleadotipo) VALUES('PROMOTOR'),('LIDER'),('MASTER');
DELETE FROM rhm_empleadoestatus;
INSERT INTO rhm_empleadoestatus (estatus) VALUES('Activo'),('Inactivo');
DELETE FROM lyt_comisionporcentajecat;
INSERT INTO lyt_comisionporcentajecat (alias_porcentaje_comision) VALUES('Distribución Oficial TELMEX'),('Distribución interna TELMEX');
DELETE FROM lyt_estadocuentastatus;
INSERT INTO lyt_estadocuentastatus (id_estatus_carga,estatus_carga) VALUES (1,'Iniciado'),(2,'Procesando'),(3,'Finalizado'),(4,'Fallido'),(5,'Archivo No Encontrado');