DELETE FROM rhm_empleadoperfil;
INSERT INTO rhm_empleadoperfil (perfil) VALUES('Promotor'),('Cliente');
DELETE FROM rhm_genero;
INSERT INTO rhm_genero (genero) VALUES('MASCULINO'),('FEMENIDO');
DELETE FROM rhm_tipocliente;
INSERT INTO rhm_tipocliente (tipo_cliente) VALUES('RECIDENCIAL'),('COMERCIAL'),('SOLO EN LINEA'),('MIGRACIONES');
DELETE FROM lyt_tiposervicio;
INSERT INTO lyt_tiposervicio (tipo_servicio) VALUES('ALTA NUEVA'),('ACTIVACIONES'),('UPSELL'),('OTROS SERVICIOS'),('PORTABILIDADES');
DELETE FROM rhm_empleadotipo;
INSERT INTO rhm_empleadotipo (empleadotipo) VALUES('PROMOTOR'),('LIDER'),('MASTER');
DELETE FROM rhm_empleadoperfil;
INSERT INTO rhm_empleadoperfil (perfil) VALUES('General'),('Ventas');
DELETE FROM rhm_empleadoestatus;
INSERT INTO rhm_empleadoestatus (estatus) VALUES('Activo'),('Inactivo');
DELETE FROM lyt_comisionporcentajecat;
INSERT INTO lyt_comisionporcentajecat (alias_porcentaje_comision) VALUES('Distribución Oficial TELMEX'),('Distribución interna TELMEX');
DELETE FROM lyt_estadocuentastatus;
INSERT INTO lyt_estadocuentastatus (id_estatus_carga,estatus_carga) VALUES (1,'Iniciado'),(2,'Procesando'),(3,'Finalizado'),(4,'Fallido'),(5,'Archivo No Encontrado');